export const BOTAO_CLICADO_SUCCESS = 'BOTAO_CLICADO';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
